<?php

declare(strict_types=1);

/**
 * Menu IDs for the Account Receivable module (MENUID 1024 parent).
 * Auto-generated by scripts/gen-kerisi-ar-registry.mjs
 */
return [
    'menu_ids' => [
        1045,
        1581,
        1582,
        1590,
        1598,
        1652,
        1656,
        1720,
        1728,
        1740,
        1741,
        1742,
        1757,
        1758,
        1761,
        1787,
        1789,
        1936,
        2108,
        2117,
        2183,
        2347,
        2348,
        2370,
        2500,
        2528,
        2572,
        2939,
        3249,
        3275,
        3280,
        3507,
    ],
];
